import type { SceneSpec, DataVizSceneSpec } from "../types";
import { toComponentName, j } from "./util";

export function generateDataVizSceneTsx(spec: SceneSpec): string {
  const scene = spec.scene as DataVizSceneSpec;
  const componentName = toComponentName(spec.name);
  const palette = spec.style.palette;
  const lt = spec.style.labelTypography;
  const font = spec.style.fonts.primary.family;

  const inner =
    scene.variant === "counter"
      ? emitCounter(scene, palette, font, spec.width)
      : scene.variant === "bar"
        ? emitBars(scene, palette, font)
        : emitLine(scene, palette, font);

  return `// AUTO-GENERATED by MAPANISY — edit in the studio, not here.
// Scene: ${spec.name}  ·  ${spec.durationSec}s @ ${spec.fps}fps  ·  ${spec.width}x${spec.height}

import React from "react";
import { AbsoluteFill, interpolate, useCurrentFrame, spring, useVideoConfig } from "remotion";

const CONFIG = {
  borderColor: ${j(palette.borderColor)},
  glowColor: ${j(palette.glowColor)},
  dotColor: ${j(palette.dotColor)},
  accent: ${j(scene.accentColor ?? palette.borderColor)},
  title: ${j(scene.labels.title)},
  subtitle: ${j(scene.labels.subtitle)},
  inFrame: ${scene.reveal.inFrame},
  holdFrame: ${scene.reveal.holdFrame},
  outFrame: ${scene.reveal.outFrame},
};

const formatN = (n: number, prefix = "", suffix = "", decimals = 0, separator = true) =>
  \`\${prefix}\${n.toLocaleString("en-US", { minimumFractionDigits: decimals, maximumFractionDigits: decimals, useGrouping: separator })}\${suffix}\`;

export const ${componentName}: React.FC = () => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();

  const titleOp = interpolate(frame,
    [CONFIG.inFrame, CONFIG.inFrame + 8, CONFIG.outFrame - 12, CONFIG.outFrame],
    [0, 1, 1, 0],
    { extrapolateLeft: "clamp", extrapolateRight: "clamp" });

  const progress = spring({
    frame: frame - CONFIG.inFrame - 4, fps,
    config: { damping: 18, mass: 0.9 },
    durationInFrames: CONFIG.holdFrame - CONFIG.inFrame,
  });

  return (
    <AbsoluteFill style={{ background: "#06080f" }}>
      <div style={{
        position: "absolute", top: "16%", left: 0, right: 0,
        textAlign: "center", opacity: titleOp,
      }}>
        <div style={{
          fontFamily: ${j(`'${font}', 'Inter', Arial, sans-serif`)},
          fontSize: ${Math.round(lt.subSize * 1.2)}, fontWeight: 300, letterSpacing: ${lt.subSpacing},
          color: CONFIG.accent, opacity: 0.9,
        }}>{CONFIG.subtitle}</div>
        <div style={{
          marginTop: 32,
          fontFamily: ${j(`'${font}', 'Inter', Arial, sans-serif`)},
          fontSize: ${Math.round(lt.titleSize * 0.7)}, fontWeight: 300, letterSpacing: ${Math.round(lt.titleSpacing * 0.6)},
          color: "#ffffff",
        }}>{CONFIG.title}</div>
      </div>

      <AbsoluteFill style={{ alignItems: "center", justifyContent: "center" }}>
${inner}
      </AbsoluteFill>
    </AbsoluteFill>
  );
};
`;
}

function emitCounter(scene: DataVizSceneSpec, palette: any, font: string, width: number) {
  const value = scene.data.value ?? 0;
  const prefix = scene.data.prefix ?? "";
  const suffix = scene.data.suffix ?? "";
  const decimals = scene.data.decimals ?? 0;
  const separator = scene.data.separator ?? true;
  return `        <div style={{ textAlign: "center", opacity: titleOp }}>
          <div style={{
            fontFamily: ${j(`'${font}', 'Inter', Arial, sans-serif`)},
            fontSize: ${Math.round(width * 0.12)}, fontWeight: 200, letterSpacing: -4,
            color: CONFIG.accent,
            textShadow: \`0 0 80px \${CONFIG.glowColor}99\`,
            lineHeight: 1, fontVariantNumeric: "tabular-nums",
          }}>
            {formatN(${value} * progress, ${j(prefix)}, ${j(suffix)}, ${decimals}, ${separator})}
          </div>
        </div>`;
}

function emitBars(scene: DataVizSceneSpec, palette: any, font: string) {
  const bars = scene.data.bars ?? [];
  return `        <div style={{ display: "flex", gap: 40, alignItems: "flex-end", height: 800, opacity: titleOp }}>
          {${JSON.stringify(bars)}.map((b: { label: string; value: number }, i: number) => {
            const max = Math.max(...${JSON.stringify(bars.map((b) => b.value))}, 1);
            const h = (b.value / max) * 700 * progress;
            return (
              <div key={i} style={{ display: "flex", flexDirection: "column", alignItems: "center", gap: 18 }}>
                <div style={{ fontFamily: ${j(`'${font}', 'Inter', Arial, sans-serif`)}, fontSize: 36, color: "#fff", fontVariantNumeric: "tabular-nums" }}>
                  {Math.round(b.value * progress).toLocaleString()}
                </div>
                <div style={{
                  width: 180, height: h,
                  background: \`linear-gradient(180deg, \${CONFIG.glowColor}, \${CONFIG.accent})\`,
                  boxShadow: \`0 0 40px \${CONFIG.glowColor}80\`,
                }} />
                <div style={{ fontFamily: ${j(`'${font}', 'Inter', Arial, sans-serif`)}, fontSize: 28, color: "rgba(255,255,255,0.75)", letterSpacing: 4 }}>
                  {b.label}
                </div>
              </div>
            );
          })}
        </div>`;
}

function emitLine(scene: DataVizSceneSpec, palette: any, font: string) {
  const points = scene.data.points ?? [];
  return `        {(() => {
          const points = ${JSON.stringify(points)};
          if (points.length < 2) return null;
          const W = 1800, H = 600;
          const max = Math.max(...points.map((p: any) => p.value), 1);
          const visibleCount = Math.max(2, Math.floor(points.length * progress));
          const visible = points.slice(0, visibleCount);
          const path = visible.map((p: any, i: number) => {
            const x = (i / (points.length - 1)) * W;
            const y = H - (p.value / max) * H;
            return \`\${i === 0 ? "M" : "L"} \${x} \${y}\`;
          }).join(" ");
          return (
            <svg width={W} height={H} style={{ opacity: titleOp, overflow: "visible" }}>
              <path d={path} fill="none" stroke={CONFIG.accent} strokeWidth={6}
                strokeLinecap="round" strokeLinejoin="round"
                style={{ filter: \`drop-shadow(0 0 24px \${CONFIG.glowColor}cc)\` }} />
              {visible.map((p: any, i: number) => {
                const x = (i / (points.length - 1)) * W;
                const y = H - (p.value / max) * H;
                return (
                  <g key={i}>
                    <circle cx={x} cy={y} r={10} fill={CONFIG.accent} />
                    <text x={x} y={H + 50} fill="#fff" fontSize={28}
                      fontFamily={${j(`'${font}', 'Inter', Arial, sans-serif`)}} textAnchor="middle" opacity={0.7}>
                      {p.label}
                    </text>
                  </g>
                );
              })}
            </svg>
          );
        })()}`;
}
