import type { SceneSpec, LowerThirdSceneSpec } from "../types";
import { toComponentName, j } from "./util";

export function generateLowerThirdSceneTsx(spec: SceneSpec): string {
  const s = spec.scene as LowerThirdSceneSpec;
  const componentName = toComponentName(spec.name);
  const { palette, fonts, labelTypography } = spec.style;
  const fontExpr = j(`'${fonts.primary.family}', 'Inter', Arial, sans-serif`);

  const sideStyle =
    s.position === "left"
      ? `{ left: ${Math.round(spec.width * 0.06)}, alignItems: "flex-start", textAlign: "left" as const }`
      : `{ right: ${Math.round(spec.width * 0.06)}, left: "auto", alignItems: "flex-end", textAlign: "right" as const }`;

  const flexDir = s.position === "left" ? `"row"` : `"row-reverse"`;
  const animation = s.animation ?? "slide";
  const fontScale = s.fontScale ?? 1;
  const accent = s.accentColor ?? palette.borderColor;
  const titleSize = Math.round(labelTypography.titleSize * fontScale);
  const subSize = Math.round(labelTypography.subSize * fontScale);
  const slideFrom = animation === "slide" ? (s.position === "left" ? -80 : 80) : 0;
  // Wipe clip-path endpoints (inset from the side opposite the anchor).
  const wipeClip =
    animation === "wipe"
      ? s.position === "left"
        ? "`inset(0 ${100 - wipePct}% 0 0)`"
        : "`inset(0 0 0 ${100 - wipePct}%)`"
      : "undefined";

  return `// AUTO-GENERATED by MAPANISY — edit in the studio, not here.
// Scene: ${spec.name}  ·  ${spec.durationSec}s @ ${spec.fps}fps  ·  ${spec.width}x${spec.height}

import React from "react";
import { AbsoluteFill, interpolate, useCurrentFrame } from "remotion";

const CONFIG = {
  name: ${j(s.name)},
  role: ${j(s.role)},
  inFrame: ${s.reveal.inFrame},
  outFrame: ${s.reveal.outFrame},
  borderColor: ${j(palette.borderColor)},
  accentColor: ${j(accent)},
  glowColor: ${j(palette.glowColor)},
};

export const ${componentName}: React.FC = () => {
  const frame = useCurrentFrame();
  const op = interpolate(frame, [CONFIG.inFrame, CONFIG.inFrame + 8, CONFIG.outFrame - 16, CONFIG.outFrame], [0, 1, 1, 0], { extrapolateLeft: "clamp", extrapolateRight: "clamp" });
  const slideX = interpolate(frame, [CONFIG.inFrame, CONFIG.inFrame + 14], [${slideFrom}, 0], { extrapolateLeft: "clamp", extrapolateRight: "clamp" });
  const barW = interpolate(frame, [CONFIG.inFrame + 4, CONFIG.inFrame + 20], [0, 12], { extrapolateLeft: "clamp", extrapolateRight: "clamp" });
  const wipePct = interpolate(frame, [CONFIG.inFrame, CONFIG.inFrame + 16], [0, 100], { extrapolateLeft: "clamp", extrapolateRight: "clamp" });

  return (
    <AbsoluteFill style={{ background: "transparent" }}>
      <div style={{
        position: "absolute",
        bottom: ${Math.round(spec.height * 0.12)},
        display: "flex", flexDirection: "column", gap: 18,
        opacity: op, transform: \`translateX(\${slideX}px)\`,
        clipPath: ${wipeClip},
        ...${sideStyle},
      }}>
        <div style={{ display: "flex", alignItems: "center", gap: 28, flexDirection: ${flexDir} }}>
          ${s.accentBar ? `<div style={{
            width: barW,
            height: ${Math.round(titleSize * 1.3)},
            background: CONFIG.accentColor,
            boxShadow: \`0 0 24px \${CONFIG.glowColor}cc\`,
          }} />` : ""}
          <div style={{
            padding: "18px 36px",
            background: "rgba(6,8,15,0.7)",
            backdropFilter: "blur(8px)",
            border: \`1px solid \${CONFIG.borderColor}55\`,
          }}>
            <div style={{
              fontFamily: ${fontExpr},
              fontSize: ${titleSize}, fontWeight: 300,
              letterSpacing: ${Math.round(labelTypography.titleSpacing * 0.7)},
              color: "#ffffff", lineHeight: 1,
            }}>{CONFIG.name}</div>
            <div style={{
              marginTop: 14,
              fontFamily: ${fontExpr},
              fontSize: ${subSize}, fontWeight: 300,
              letterSpacing: ${labelTypography.subSpacing},
              color: CONFIG.accentColor, opacity: 0.92,
            }}>{CONFIG.role}</div>
          </div>
        </div>
      </div>
    </AbsoluteFill>
  );
};
`;
}
