import type { SceneSpec, MapSceneSpec } from "../types";
import { beatsToFrames } from "../beats";
import { escapeJsx, j, toComponentName } from "./util";

// Re-export so existing imports of `toComponentName` from this module work.
export { toComponentName };

/** Emit the easing function expression matching the selected EasingName */
function easingExpr(name: string): string {
  switch (name) {
    case "linear":
      return "(t: number) => t";
    case "easeIn":
      return "(t: number) => t * t";
    case "easeOut":
      return "(t: number) => t * (2 - t)";
    case "easeInOut":
      return "(t: number) => (t < 0.5 ? 2 * t * t : -1 + (4 - 2 * t) * t)";
    case "smooth":
      return "(t: number) => t * t * (3 - 2 * t)";
    case "cinematic":
      return "(t: number) => t * t * t * (t * (6 * t - 15) + 10)";
    default:
      return "(t: number) => (t < 0.5 ? 2 * t * t : -1 + (4 - 2 * t) * t)";
  }
}

/**
 * Emits a standalone Remotion TSX file that mirrors the structure of
 * Scene02-NanshanMapbox.tsx. The exported file depends only on:
 *   - remotion
 *   - react-map-gl
 *   - mapbox-gl
 *
 * MAPBOX_TOKEN is inlined at generation time from NEXT_PUBLIC_MAPBOX_TOKEN —
 * the file is fully self-contained and does not import from the host project.
 */
export function generateMapSceneTsx(spec: SceneSpec): string {
  // Read the public Mapbox token at generation time. This is intentionally a
  // NEXT_PUBLIC_ key (safe to embed in client bundles and generated files).
  const mapboxToken = process.env.NEXT_PUBLIC_MAPBOX_TOKEN ?? "";
  const scene = spec.scene as MapSceneSpec;
  const FRAMES = spec.durationSec * spec.fps;
  // Convert fraction beats to absolute frames for the emitted code
  const beats = beatsToFrames(scene.beats, FRAMES);
  const easing = scene.easing ?? { phase1: "easeInOut", phase2: "smooth" };
  const palette = spec.style.palette;
  const labels = scene.labels;
  const lt = spec.style.labelTypography;
  const componentName = toComponentName(spec.name);
  const isTransparent = scene.transparentBg === true;
  // Multi-highlight: support both new highlights[] and legacy single highlight
  const highlightsList: any[] = Array.isArray(scene.highlights)
    ? scene.highlights
    : scene.highlight
      ? [scene.highlight]
      : [];
  const hasHighlights = highlightsList.length > 0;
  const hasRoute = !!(scene.route && scene.route.coordinates?.length > 1);
  const routeAnimStyle = (scene.route?.animationStyle ?? "draw") as
    | "draw" | "fade" | "dotted-flow" | "static";
  const showStreets = scene.showStreets !== false;
  const showLabels = scene.showLabels !== false;

  const labelsTsx = labels
    .map((label, i) => emitLabel(label, i, palette, lt, spec.style.fonts.primary.family, spec.width, spec.height, FRAMES))
    .join("\n\n      ");

  return `// AUTO-GENERATED by MAPANISY — edit in the studio, not here.
// Scene: ${spec.name}  ·  ${spec.durationSec}s @ ${spec.fps}fps  ·  ${spec.width}x${spec.height}

import React, { useState, useCallback, useRef, useEffect } from "react";
import {
  AbsoluteFill,
  interpolate,
  useCurrentFrame,
  delayRender,
  continueRender,
} from "remotion";
// (interpolate above is wrapped by sInterp below for safety)
import Map, { MapRef, Source, Layer } from "react-map-gl/mapbox";
import "mapbox-gl/dist/mapbox-gl.css";
// Token inlined at export time — no external config file needed.
const MAPBOX_TOKEN = ${JSON.stringify(mapboxToken)};

// Mapbox style: real URL when opaque, empty (transparent) style for overlay export
${isTransparent
  ? `const MAP_STYLE: any = { version: 8, sources: {}, layers: [{ id: "_bg", type: "background", paint: { "background-color": "rgba(0,0,0,0)" } }] };`
  : `const MAP_STYLE = ${JSON.stringify(scene.mapStyleUrl)};`}

// Camera path: [start, mid?, ...extraWaypoints, end] — multi-phase pan
const WAYPOINTS: { lon: number; lat: number; zoom: number; pitch?: number; bearing?: number }[] = ${JSON.stringify([
  scene.start,
  ...(scene.mid ? [scene.mid] : []),
  ...(scene.extraWaypoints ?? []),
  scene.end,
])};
const SMOOTH_PATH = ${scene.smoothCameraPath !== false};
const SHOW_3D_BUILDINGS = ${!!scene.show3dBuildings};
const TERRAIN = ${JSON.stringify(scene.terrain ?? { enabled: false, exaggeration: 1 })};

// Camera path helpers (inlined from src/lib/interp.ts for self-contained exports)
const _catmullRom = (p0: number, p1: number, p2: number, p3: number, t: number): number => {
  const t2 = t * t, t3 = t2 * t;
  return 0.5 * (2*p1 + (-p0+p2)*t + (2*p0-5*p1+4*p2-p3)*t2 + (-p0+3*p1-3*p2+p3)*t3);
};
const _catmullRomChain = (values: number[], progress: number): number => {
  const N = values.length;
  if (N === 0) return 0;
  if (N === 1) return values[0];
  if (N === 2) return values[0] + (values[1] - values[0]) * progress;
  const c = Math.max(0, Math.min(1, progress));
  const seg = Math.min(N - 2, Math.floor(c * (N - 1)));
  const segT = c * (N - 1) - seg;
  const p1 = values[seg], p2 = values[seg + 1];
  const p0 = seg === 0 ? 2 * p1 - p2 : values[seg - 1];
  const p3 = seg + 2 >= N ? 2 * p2 - p1 : values[seg + 2];
  return _catmullRom(p0, p1, p2, p3, segT);
};
// linearChain: piecewise linear with smoothstep easing per segment.
// CAN'T overshoot — used for zoom/pitch to kill terrain wobble.
const _linearChain = (values: number[], progress: number): number => {
  const N = values.length;
  if (N === 0) return 0;
  if (N === 1) return values[0];
  if (N === 2) {
    const t = Math.max(0, Math.min(1, progress));
    const sm = t * t * (3 - 2 * t);
    return values[0] + (values[1] - values[0]) * sm;
  }
  const c = Math.max(0, Math.min(1, progress));
  const seg = Math.min(N - 2, Math.floor(c * (N - 1)));
  const t = c * (N - 1) - seg;
  const sm = t * t * (3 - 2 * t);
  return values[seg] + (values[seg + 1] - values[seg]) * sm;
};

// Route helpers (mirrors src/remotion/MapScene.tsx). Ease-in-out cubic shared
// by the line draw, vehicle icon and camera-follow so nothing desyncs; plus an
// arc-length sampler for constant-speed, interpolated motion along the path.
const _routeEase = (p: number): number =>
  p < 0.5 ? 4 * p * p * p : 1 - Math.pow(-2 * p + 2, 3) / 2;
const _sampleRouteAt = (coords: [number, number][], t: number): { lon: number; lat: number; bearing: number } => {
  const n = coords.length;
  if (n === 0) return { lon: 0, lat: 0, bearing: 0 };
  if (n === 1) return { lon: coords[0][0], lat: coords[0][1], bearing: 0 };
  const seg: number[] = []; let total = 0;
  for (let i = 0; i < n - 1; i++) { const d = Math.hypot(coords[i+1][0]-coords[i][0], coords[i+1][1]-coords[i][1]); seg.push(d); total += d; }
  const bearingOf = (a: [number, number], b: [number, number]) => (Math.atan2(b[0]-a[0], b[1]-a[1]) * 180) / Math.PI;
  if (total === 0) return { lon: coords[0][0], lat: coords[0][1], bearing: 0 };
  const c = Math.max(0, Math.min(1, t));
  if (c <= 0) return { lon: coords[0][0], lat: coords[0][1], bearing: bearingOf(coords[0], coords[1]) };
  if (c >= 1) return { lon: coords[n-1][0], lat: coords[n-1][1], bearing: bearingOf(coords[n-2], coords[n-1]) };
  let target = c * total;
  for (let i = 0; i < seg.length; i++) {
    if (target <= seg[i] || i === seg.length - 1) {
      const f = seg[i] > 0 ? target / seg[i] : 0;
      const a = coords[i], b = coords[i+1];
      return { lon: a[0]+(b[0]-a[0])*f, lat: a[1]+(b[1]-a[1])*f, bearing: bearingOf(a, b) };
    }
    target -= seg[i];
  }
  const last = coords[n-1];
  return { lon: last[0], lat: last[1], bearing: bearingOf(coords[n-2], last) };
};

const CONFIG = {
  endPitch: ${scene.end.pitch},
  endBearing: ${scene.end.bearing},

  hold: ${beats.hold},
  breathe: ${beats.breathe},
  arrive: ${beats.arrive},

  borderColor: ${j(palette.borderColor)},
  glowColor: ${j(palette.glowColor)},
  fillColor: ${j(palette.fillColor)},
  dotColor: ${j(palette.dotColor)},
  ringColor: ${j(palette.ringColor)},
};

${hasHighlights ? `// Inline highlight geometries — N highlights each with their own style
const HIGHLIGHTS: { geojson: any; style: any; name: string; placeType: string }[] = ${JSON.stringify(highlightsList)};` : ""}

${hasRoute ? `// Inline route geometry resolved by /api/route (Mapbox Directions or great-circle)
const ROUTE_COORDS: [number, number][] = ${JSON.stringify(scene.route!.coordinates)};
const ROUTE_STYLE = ${JSON.stringify(scene.route!.style, null, 2)};
const ROUTE_ICON = ${JSON.stringify(scene.route!.icon, null, 2)};
const ROUTE_DRAW_DURATION = ${scene.route!.drawDuration ?? 0.7};
const ROUTE_ANIM_STYLE = ${JSON.stringify(routeAnimStyle)};` : ""}

const SHOW_STREETS = ${showStreets};
const SHOW_LABELS = ${showLabels};
${hasHighlights ? emitCentroidHelper() : ""}

const FRAMES = ${FRAMES};

// Phase easing — selected in MAPANISY (phase1=${easing.phase1}, phase2=${easing.phase2})
const ease1 = ${easingExpr(easing.phase1)};
const ease2 = ${easingExpr(easing.phase2)};

// safeInterpolate: drop-in replacement for Remotion's interpolate that
// never throws on degenerate ranges (e.g. start.zoom === end.zoom).
const fixMonotonic = (arr: number[]) => {
  const out = [arr[0]];
  for (let i = 1; i < arr.length; i++) {
    out.push(arr[i] <= out[i - 1] ? out[i - 1] + 0.001 : arr[i]);
  }
  return out;
};
const sInterp = (
  input: number,
  range: number[],
  output: number[],
  opts?: { extrapolateLeft?: "clamp" | "extend"; extrapolateRight?: "clamp" | "extend" }
) => interpolate(input, fixMonotonic(range), output, opts);

export const ${componentName}: React.FC = () => {
  const frame = useCurrentFrame();
  const mapRef = useRef<MapRef>(null);

  // Three render-blockers: tiles, fonts, and route geometry resolution.
  const [tilesHandle] = useState(() =>
    delayRender("Waiting for Mapbox tiles", { timeoutInMilliseconds: 90000 })
  );
  const [fontsHandle] = useState(() =>
    delayRender("Waiting for fonts", { timeoutInMilliseconds: 30000 })
  );
  useEffect(() => {
    if (typeof document === "undefined") { continueRender(fontsHandle); return; }
    document.fonts.ready.then(() => continueRender(fontsHandle)).catch(() => continueRender(fontsHandle));
  }, [fontsHandle]);

  const continued = useRef(false);
  const onMapIdle = useCallback(() => {
    if (!continued.current) {
      continued.current = true;
      const map = mapRef.current?.getMap();
      if (map) {
        try {
          const style = map.getStyle();
          if (style && style.layers) {
            for (const layer of style.layers) {
              const id = (layer.id || "").toLowerCase();
              const type = layer.type;
              const isStreet =
                id.includes("road") || id.includes("street") || id.includes("highway") ||
                id.includes("motorway") || id.includes("path") || id.includes("track") ||
                id.includes("tunnel") || id.includes("bridge");
              const isLabel = type === "symbol";
              try {
                if (isStreet && !SHOW_STREETS) {
                  map.setLayoutProperty(layer.id, "visibility", "none");
                } else if (isLabel && !SHOW_LABELS) {
                  map.setLayoutProperty(layer.id, "visibility", "none");
                }
              } catch {}
            }
          }
        } catch {}
      }
      continueRender(tilesHandle);
    }
  }, [tilesHandle]);

  // Multi-waypoint pan — Catmull-Rom (smooth) or linear per-phase fallback
  const N = WAYPOINTS.length;
  const useSmooth = SMOOTH_PATH && N >= 3;
  const animProgress = sInterp(frame, [0, CONFIG.arrive], [0, 1], {
    extrapolateLeft: "clamp", extrapolateRight: "clamp",
  });
  let lonBase: number, latBase: number, zoomBase: number, pitchBase: number, bearingBase: number;
  if (useSmooth) {
    const t = ease1(animProgress);
    lonBase  = _catmullRomChain(WAYPOINTS.map(w => w.lon), t);
    latBase  = _catmullRomChain(WAYPOINTS.map(w => w.lat), t);
    // Zoom/pitch use linear-with-smoothstep — CAN'T overshoot, no wobble
    zoomBase = _linearChain(WAYPOINTS.map(w => w.zoom), t);
    pitchBase = _linearChain(WAYPOINTS.map(w => w.pitch ?? 0), t);
    bearingBase = _linearChain(WAYPOINTS.map(w => w.bearing ?? CONFIG.endBearing), t);
  } else {
    const perPhase = N > 1 ? CONFIG.arrive / (N - 1) : CONFIG.arrive;
    const rawPhase = Math.min(N - 2, Math.floor(frame / Math.max(1, perPhase)));
    const phaseStart = rawPhase * perPhase;
    const phaseEnd = (rawPhase + 1) * perPhase;
    const easingFn = rawPhase === 0 ? ease1 : ease2;
    const tRaw = sInterp(frame, [phaseStart, phaseEnd], [0, 1], {
      extrapolateLeft: "clamp", extrapolateRight: "clamp",
    });
    const t = easingFn(tRaw);
    const a = WAYPOINTS[rawPhase];
    const b = WAYPOINTS[Math.min(N - 1, rawPhase + 1)];
    lonBase  = sInterp(t, [0, 1], [a.lon, b.lon]);
    latBase  = sInterp(t, [0, 1], [a.lat, b.lat]);
    zoomBase = sInterp(t, [0, 1], [a.zoom, b.zoom]);
    pitchBase = sInterp(t, [0, 1], [a.pitch ?? 0, b.pitch ?? 0]);
    bearingBase = sInterp(t, [0, 1], [a.bearing ?? 0, b.bearing ?? CONFIG.endBearing]);
  }
  const microZoom = sInterp(frame, [CONFIG.arrive, FRAMES], [0, 0.18], {
    extrapolateLeft: "clamp", extrapolateRight: "clamp",
  });
  let longitude = lonBase;
  let latitude = latBase;
  let zoom = zoomBase + microZoom;
  let pitch = pitchBase;
  let bearing = bearingBase;
  ${scene.route?.followCamera ? `// B3: camera follows route
  if (ROUTE_COORDS.length > 1) {
    const drawEnd = Math.max(1, Math.round(ROUTE_DRAW_DURATION * FRAMES));
    const progress = _routeEase(Math.max(0, Math.min(1, frame / drawEnd)));
    const s = _sampleRouteAt(ROUTE_COORDS, progress);
    longitude = s.lon;
    latitude = s.lat;
  }` : ""}

  const highlightAlpha = sInterp(frame, [CONFIG.hold, CONFIG.breathe], [0, 1],
    { extrapolateLeft: "clamp", extrapolateRight: "clamp" });
  const pulse = 0.5 + 0.5 * Math.sin((frame - CONFIG.breathe) / 6);
  const highlightBorderOp = highlightAlpha;
  const highlightGlowOp = highlightAlpha * (0.55 + 0.10 * pulse);

  return (
    <AbsoluteFill style={{ background: ${isTransparent ? `"transparent"` : `"#06080f"`} }}>
      <Map
        ref={mapRef}
        mapboxAccessToken={MAPBOX_TOKEN}
        mapStyle={MAP_STYLE}
        maxTileCacheSize={1000}
        fadeDuration={0}
        // Terrain: smoothstep ramp + quantize to 0.05 to prevent per-frame re-tiling
        terrain={TERRAIN.enabled ? {
          source: "mapbox-dem",
          exaggeration: (() => {
            const t = Math.max(0, Math.min(1, (zoom - 6) / 4));
            const ramp = t * t * (3 - 2 * t);
            return Math.round(TERRAIN.exaggeration * ramp * 20) / 20;
          })(),
        } : undefined}
        longitude={longitude}
        latitude={latitude}
        zoom={zoom}
        bearing={bearing}
        pitch={pitch}
        style={{ width: ${spec.width}, height: ${spec.height} }}
        onIdle={onMapIdle}
        interactive={false}
        attributionControl={false}
        renderWorldCopies={false}
        projection={{ name: "mercator" }}
      >
        {TERRAIN.enabled && (
          <Source id="mapbox-dem" type="raster-dem" url="mapbox://mapbox.mapbox-terrain-dem-v1" tileSize={512} maxzoom={14} />
        )}
        {SHOW_3D_BUILDINGS && (
          <Layer id="3d-buildings" source="composite" source-layer="building" type="fill-extrusion" minzoom={12}
            filter={["==", ["get", "extrude"], "true"]}
            paint={{ "fill-extrusion-color": "#aaa", "fill-extrusion-height": ["get", "height"], "fill-extrusion-base": ["get", "min_height"], "fill-extrusion-opacity": 0.6 }} />
        )}
${hasHighlights ? emitHighlightLayers() : "        {/* no highlights */}"}
${hasRoute ? emitRouteLayers() : "        {/* no route */}"}
      </Map>

      ${hasHighlights ? emitHighlightLabels() : "{/* no highlight labels */}"}
      ${hasHighlights ? emitFlagBadges() : "{/* no flag badges */}"}
      ${hasRoute ? emitStopMarkers(spec) : "{/* no stop markers */}"}
      ${hasRoute ? emitRouteIcon(spec) : "{/* no route icon */}"}

      ${labelsTsx}

${isTransparent || spec.style.letterboxHeight <= 0 ? `      {/* no letterbox (transparent overlay mode) */}` : `      <AbsoluteFill style={{ pointerEvents: "none" }}>
        <div style={{ position: "absolute", top: 0, left: 0, right: 0, height: ${spec.style.letterboxHeight},
          background: "linear-gradient(to bottom, rgba(0,0,0,0.75), rgba(0,0,0,0))" }} />
        <div style={{ position: "absolute", bottom: 0, left: 0, right: 0, height: ${spec.style.letterboxHeight},
          background: "linear-gradient(to top, rgba(0,0,0,0.75), rgba(0,0,0,0))" }} />
      </AbsoluteFill>`}
    </AbsoluteFill>
  );
};
`;
}

function emitRouteLayers() {
  return `        {(() => {
          const drawEnd = Math.max(1, Math.round(ROUTE_DRAW_DURATION * FRAMES));
          const rawProgress = Math.max(0, Math.min(1, frame / drawEnd));
          const progress = _routeEase(rawProgress);
          const routeData = { type: "Feature" as const, properties: {},
            geometry: { type: "LineString" as const, coordinates: ROUTE_COORDS } };
          const baseOpacity = ROUTE_ANIM_STYLE === "fade" ? progress
            : ROUTE_ANIM_STYLE === "static" ? 1 : 1;
          const trimPaint: any = ROUTE_ANIM_STYLE === "draw"
            ? { "line-trim-offset": [0, 1 - progress] }
            : {};
          const dashFlowPaint: any = ROUTE_ANIM_STYLE === "dotted-flow"
            ? { "line-dasharray": [Math.max(0.01, 1 - (frame % 12) / 12), 1.5] }
            : (ROUTE_STYLE.dashed ? { "line-dasharray": [2, 1] } : {});
          // Leading comet head — bright moving dot on the line tip while drawing.
          const drawing = ROUTE_ANIM_STYLE === "draw" && rawProgress < 1;
          const head = drawing ? _sampleRouteAt(ROUTE_COORDS, progress) : null;
          const headData = head ? { type: "Feature" as const, properties: {},
            geometry: { type: "Point" as const, coordinates: [head.lon, head.lat] } } : null;
          const headPulse = 1 + 0.18 * Math.sin(frame / 4);
          return (
            <>
              {/* GHOST — solid bright underlay so the route is never invisible */}
              <Source id="route-ghost" type="geojson" data={routeData}>
                <Layer id="route-ghost-casing" type="line"
                  paint={{ "line-color": ROUTE_STYLE.casingColor,
                           "line-width": Math.max(2, ROUTE_STYLE.width * 0.8),
                           "line-opacity": 0.5 }}
                  layout={{ "line-cap": "round", "line-join": "round" }} />
                <Layer id="route-ghost-line" type="line"
                  paint={{ "line-color": ROUTE_STYLE.color,
                           "line-width": Math.max(1, ROUTE_STYLE.width * 0.4),
                           "line-opacity": 0.45 }}
                  layout={{ "line-cap": "round", "line-join": "round" }} />
              </Source>
              {/* Animated main route */}
              <Source id="route-drawn" type="geojson" data={routeData}>
                <Layer id="route-casing" type="line"
                  paint={{ "line-color": ROUTE_STYLE.casingColor,
                           "line-width": ROUTE_STYLE.casingWidth,
                           "line-opacity": 0.85 * baseOpacity, ...trimPaint }}
                  layout={{ "line-cap": "round", "line-join": "round" }} />
                <Layer id="route-glow" type="line"
                  paint={{ "line-color": ROUTE_STYLE.glowColor,
                           "line-width": ROUTE_STYLE.glowWidth,
                           "line-blur": 8, "line-opacity": 0.7 * baseOpacity,
                           ...trimPaint }}
                  layout={{ "line-cap": "round", "line-join": "round" }} />
                <Layer id="route-line" type="line"
                  paint={{ "line-color": ROUTE_STYLE.color,
                           "line-width": ROUTE_STYLE.width,
                           "line-opacity": baseOpacity,
                           ...trimPaint, ...dashFlowPaint }}
                  layout={{ "line-cap": "round", "line-join": "round" }} />
              </Source>
              {headData && (
                <Source id="route-head" type="geojson" data={headData}>
                  <Layer id="route-head-glow" type="circle"
                    paint={{ "circle-radius": Math.max(10, ROUTE_STYLE.width * 2.6) * headPulse,
                             "circle-color": ROUTE_STYLE.glowColor, "circle-opacity": 0.35, "circle-blur": 1 }} />
                  <Layer id="route-head-ring" type="circle"
                    paint={{ "circle-radius": Math.max(5, ROUTE_STYLE.width * 1.3) * headPulse,
                             "circle-color": ROUTE_STYLE.color, "circle-opacity": 0.95 }} />
                  <Layer id="route-head-core" type="circle"
                    paint={{ "circle-radius": Math.max(2, ROUTE_STYLE.width * 0.6),
                             "circle-color": "#ffffff", "circle-opacity": 1 }} />
                </Source>
              )}
            </>
          );
        })()}`;
}

function emitStopMarkers(spec: SceneSpec) {
  const scene = spec.scene as MapSceneSpec;
  if (scene.route?.showStopMarkers === false) return "{/* stop markers disabled */}";
  const stops = [scene.route!.from, ...(scene.route!.via ?? []), scene.route!.to];
  return `{(() => {
        const STOPS = ${JSON.stringify(stops)};
        const drawEnd = Math.max(1, Math.round(ROUTE_DRAW_DURATION * FRAMES));
        const cum: number[] = [0];
        for (let i = 1; i < ROUTE_COORDS.length; i++) cum.push(cum[i-1] + Math.hypot(ROUTE_COORDS[i][0]-ROUTE_COORDS[i-1][0], ROUTE_COORDS[i][1]-ROUTE_COORDS[i-1][1]));
        const total = cum[cum.length - 1] || 1;
        const fracForStop = (lon: number, lat: number) => {
          let best = 0, bestD = Infinity;
          for (let i = 0; i < ROUTE_COORDS.length; i++) { const d = Math.hypot(ROUTE_COORDS[i][0]-lon, ROUTE_COORDS[i][1]-lat); if (d < bestD) { bestD = d; best = i; } }
          return cum[best] / total;
        };
        return STOPS.map((stop: any, si: number) => {
          const proj = mapRef.current?.getMap()?.project([stop.lon, stop.lat]);
          if (!proj) return null;
          const arriveFrame = si === 0 ? 0 : Math.round(fracForStop(stop.lon, stop.lat) * drawEnd);
          if (frame < arriveFrame - 2) return null;
          const op = sInterp(frame, [arriveFrame, arriveFrame + 8], [0, 1], { extrapolateLeft: "clamp", extrapolateRight: "clamp" });
          const dropScale = sInterp(frame, [arriveFrame, arriveFrame + 10], [0.4, 1], { extrapolateLeft: "clamp", extrapolateRight: "clamp" });
          const pingT = (frame - arriveFrame) / 22;
          const showPing = pingT >= 0 && pingT <= 1;
          const pingR = 14 + 26 * pingT;
          const pingOp = showPing ? (1 - pingT) * 0.7 : 0;
          const baseR = 14;
          return (
            <div key={"stop-marker-" + si} style={{
              position: "absolute", left: proj.x, top: proj.y,
              transform: "translate(-50%, -50%) scale(" + dropScale + ")", opacity: op, pointerEvents: "none",
            }}>
              <svg width={100} height={100} viewBox="0 0 100 100" style={{ display: "block" }}>
                {showPing && <circle cx="50" cy="50" r={pingR} fill="none" stroke={ROUTE_STYLE.color} strokeWidth="2.5" opacity={pingOp} />}
                <circle cx="50" cy="50" r={baseR} fill={ROUTE_STYLE.color} />
                <circle cx="50" cy="50" r={baseR} fill="none" stroke={ROUTE_STYLE.casingColor} strokeWidth="2" />
                <text x="50" y="50" textAnchor="middle" dominantBaseline="central" fontSize="14" fontWeight="700" fill={ROUTE_STYLE.casingColor}>
                  {si + 1}
                </text>
              </svg>
            </div>
          );
        });
      })()}`;
}

function emitRouteIcon(spec: SceneSpec) {
  const scene = spec.scene as MapSceneSpec;
  const preset = scene.route!.icon.preset;
  const fill = scene.route!.style.color;
  const stroke = scene.route!.style.casingColor;
  const customUrl = scene.route!.icon.customUrl;

  // Inline the chosen preset SVG (or img for custom) so the exported file
  // has no external icon dependencies.
  let iconSvg: string;
  if (preset === "custom" && customUrl) {
    iconSvg = `<img src={${JSON.stringify(customUrl)}} width={size} height={size} style={{ width: size, height: size, objectFit: "contain" }} />`;
  } else {
    iconSvg = inlinePresetSvg(preset, fill, stroke);
  }

  return `{ROUTE_ICON.show && (() => {
        const drawEnd = Math.max(1, Math.round(ROUTE_DRAW_DURATION * FRAMES));
        const progress = _routeEase(Math.max(0, Math.min(1, frame / drawEnd)));
        const s = _sampleRouteAt(ROUTE_COORDS, progress);
        const proj = mapRef.current?.getMap()?.project([s.lon, s.lat]);
        if (!proj) return null;
        const bearing = s.bearing;
        const size = ROUTE_ICON.size ?? 96;
        const rot = ${preset === "aircraft" ? "bearing" : "0"};
        return (
          <div style={{
            position: "absolute", left: proj.x - size / 2, top: proj.y - size / 2,
            width: size, height: size, transform: \`rotate(\${rot}deg)\`,
            pointerEvents: "none", filter: "drop-shadow(0 4px 12px rgba(0,0,0,0.6))",
          }}>
            ${iconSvg}
          </div>
        );
      })()}`;
}

/** Inline SVG markup for each preset — keeps exported TSX dependency-free. */
function inlinePresetSvg(preset: string, fill: string, casing: string): string {
  const cFill = JSON.stringify(fill);
  const cFg = JSON.stringify(casing); // icon stroke = dark casing on colored disk
  const disk = `<circle cx="12" cy="12" r="11" fill={${cFill}}/><circle cx="12" cy="12" r="11" fill="none" stroke={${cFg}} strokeWidth="0.6" opacity="0.5"/>`;
  const stroke = `stroke={${cFg}} strokeWidth="1.6" fill="none" strokeLinecap="round" strokeLinejoin="round"`;
  switch (preset) {
    case "car":
      return `<svg viewBox="0 0 24 24" width={size} height={size}>${disk}<path ${stroke} d="M14 16H9m10 0h3v-3.15a1 1 0 0 0-.84-.99L16 11l-2.7-3.6a1 1 0 0 0-.8-.4H5.24a2 2 0 0 0-1.8 1.1l-.8 1.63A6 6 0 0 0 2 12.42V16h2"/><circle cx="6.5" cy="16.5" r="2" ${stroke}/><circle cx="16.5" cy="16.5" r="2" ${stroke}/></svg>`;
    case "bike":
      return `<svg viewBox="0 0 24 24" width={size} height={size}>${disk}<circle cx="6.5" cy="17" r="2.5" ${stroke}/><circle cx="17.5" cy="17" r="2.5" ${stroke}/><path ${stroke} d="M6.5 17l3-5h5l3 5M14.5 12l-2-4h-2M14.5 8l1.5 0"/></svg>`;
    case "walking":
      return `<svg viewBox="0 0 24 24" width={size} height={size}>${disk}<circle cx="13" cy="5" r="1.7" fill={${cFg}}/><path ${stroke} d="M9 20l3-6 2 2 1 4M9 14l3-6 3 4"/></svg>`;
    case "boat":
      return `<svg viewBox="0 0 24 24" width={size} height={size}>${disk}<path ${stroke} d="M2 21c.6.5 1.2 1 2.5 1 2.5 0 2.5-2 5-2s2.5 2 5 2 2.5-2 5-2c1.3 0 1.9.5 2.5 1"/><path ${stroke} d="M19.38 20A11.6 11.6 0 0 0 21 14l-9-4-9 4c0 2.9.94 5.34 2.81 7.76"/><path ${stroke} d="M19 13V7a2 2 0 0 0-2-2H7a2 2 0 0 0-2 2v6M12 10v3M12 2v3"/></svg>`;
    case "aircraft":
      return `<svg viewBox="0 0 24 24" width={size} height={size}>${disk}<path d="M17.8 19.2L16 11l3.5-3.5C21 6 21.5 4 21 3c-1-.5-3 0-4.5 1.5L13 8 4.8 6.2c-.5-.1-.9.1-1.1.5l-.3.5c-.2.5-.1 1 .3 1.3L9 12l-2 3H4l-1 1 3 2 2 3 1-1v-3l3-2 3.5 5.3c.3.4.8.5 1.3.3l.5-.2c.4-.3.6-.7.5-1.2z" fill={${cFg}}/></svg>`;
    default:
      return `<svg viewBox="0 0 24 24" width={size} height={size}>${disk}<circle cx="12" cy="12" r="4" fill={${cFg}}/></svg>`;
  }
}

function emitHighlightLayers() {
  return `        {HIGHLIGHTS.map((h, hi) => {
          const data = h.geojson.type === "FeatureCollection" || h.geojson.type === "Feature"
            ? h.geojson
            : { type: "Feature", geometry: h.geojson, properties: {} };
          // Per-highlight fade window if h.fade set, else global beats
          let a: number;
          if (h.fade) {
            const fIn = Math.round(h.fade.in * FRAMES);
            const fOut = Math.round(h.fade.out * FRAMES);
            a = sInterp(frame, [fIn, fIn + 8, fOut - 8, fOut], [0, 1, 1, 0],
              { extrapolateLeft: "clamp", extrapolateRight: "clamp" });
          } else {
            a = highlightAlpha;
          }
          const anim = h.animationStyle ?? "fade";
          let borderPaint: any = {}, fillPaint: any = {}, glowPaint: any = {};
          if (anim === "static") {
            borderPaint = { "line-opacity": 1, "line-width": h.style.borderWidth };
            fillPaint   = { "fill-opacity": h.style.fillOpacity };
            glowPaint   = { "line-opacity": 0.55 };
          } else if (anim === "sweep") {
            borderPaint = {
              "line-opacity": a > 0 ? 1 : 0,
              "line-width": h.style.borderWidth,
              "line-trim-offset": [0, Math.max(0, 1 - a)],
            };
            fillPaint   = { "fill-opacity": Math.max(0, (a - 0.6) / 0.4) * h.style.fillOpacity };
            glowPaint   = {
              "line-opacity": a * 0.55,
              "line-trim-offset": [0, Math.max(0, 1 - a)],
            };
          } else if (anim === "pulse-in") {
            borderPaint = { "line-opacity": a, "line-width": a * h.style.borderWidth };
            fillPaint   = { "fill-opacity": a * h.style.fillOpacity };
            glowPaint   = { "line-opacity": a * (0.55 + 0.15 * pulse) };
          } else if (anim === "border-first") {
            const br = Math.min(1, a / 0.5), fr = Math.max(0, (a - 0.5) / 0.5);
            borderPaint = { "line-opacity": br, "line-width": h.style.borderWidth };
            fillPaint   = { "fill-opacity": fr * h.style.fillOpacity };
            glowPaint   = { "line-opacity": br * 0.55 };
          } else {
            borderPaint = { "line-opacity": a, "line-width": h.style.borderWidth };
            fillPaint   = { "fill-opacity": a * h.style.fillOpacity };
            glowPaint   = { "line-opacity": a * (0.55 + 0.1 * pulse) };
          }
          return (
            <Source key={"hl-" + hi} id={"highlight-" + hi} type="geojson" data={data}>
              <Layer id={"highlight-" + hi + "-glow"} type="line"
                paint={{
                  "line-color": h.style.glowColor,
                  "line-width": h.style.glowWidth,
                  "line-blur": h.style.glowBlur,
                  ...glowPaint,
                }}
                layout={{ "line-cap": "round", "line-join": "round" }} />
              <Layer id={"highlight-" + hi + "-fill"} type="fill"
                paint={{ "fill-color": h.style.fillColor, ...fillPaint }} />
              <Layer id={"highlight-" + hi + "-border"} type="line"
                paint={{ "line-color": h.style.borderColor, ...borderPaint }}
                layout={{ "line-cap": "round", "line-join": "round" }} />
            </Source>
          );
        })}`;
}

/** Inline centroid helper for exported scenes — duplicated from src/lib/geo.ts
    so the exported file has no studio dependencies. */
function emitCentroidHelper(): string {
  return `
function _centroid(geojson: any): [number, number] {
  if (!geojson) return [0, 0];
  if (geojson.type === "FeatureCollection") return _centroid(geojson.features?.[0]);
  if (geojson.type === "Feature") return _centroid(geojson.geometry);
  const t = geojson.type, c = geojson.coordinates;
  if (!c) return [0, 0];
  const ringCentroid = (ring: number[][]) => {
    let sx = 0, sy = 0, n = 0;
    const last = ring.length;
    const closed = last > 0 && ring[0][0] === ring[last-1][0] && ring[0][1] === ring[last-1][1];
    const upto = closed ? last - 1 : last;
    for (let i = 0; i < upto; i++) { sx += ring[i][0]; sy += ring[i][1]; n++; }
    return n === 0 ? [0, 0] : [sx / n, sy / n] as [number, number];
  };
  const ringArea = (ring: number[][]) => {
    let a = 0; for (let i = 0; i < ring.length - 1; i++) a += ring[i][0]*ring[i+1][1] - ring[i+1][0]*ring[i][1];
    return Math.abs(a/2);
  };
  if (t === "Polygon") return ringCentroid(c[0]);
  if (t === "MultiPolygon") {
    let best = c[0]?.[0] ?? [], bestArea = ringArea(best);
    for (let i = 1; i < c.length; i++) {
      const r = c[i][0], ar = ringArea(r);
      if (ar > bestArea) { bestArea = ar; best = r; }
    }
    return ringCentroid(best);
  }
  if (t === "LineString") return ringCentroid(c);
  if (t === "Point") return c as [number, number];
  return [0, 0];
}
`;
}

/** Emit the highlight LABEL overlays after the Map. */
function emitHighlightLabels(): string {
  return `{HIGHLIGHTS.map((h, hi) => {
        if (!h.label?.text) return null;
        const fade = h.label.fade ?? { in: CONFIG.hold / FRAMES, out: 1 };
        const fadeInF = Math.round(fade.in * FRAMES);
        const fadeOutF = Math.round(fade.out * FRAMES);
        const labelOp = sInterp(frame, [fadeInF, fadeInF + 8, fadeOutF - 8, fadeOutF], [0, 1, 1, 0], { extrapolateLeft: "clamp", extrapolateRight: "clamp" });
        if (labelOp < 0.01) return null;
        const a = h.label.anchor ?? "centroid";
        const centroid = _centroid(h.geojson);
        let anchorPoint: [number, number] = centroid;
        const proj = mapRef.current?.getMap()?.project(anchorPoint);
        if (!proj) return null;
        const ls = h.label.style ?? {};
        const size = ls.size ?? 50;
        const subSize = ls.subSize ?? 20;
        const color = ls.color ?? "#ffffff";
        const subColor = ls.subColor ?? h.style.borderColor;
        const spacing = ls.spacing ?? 14;
        const weight = ls.weight ?? 300;
        return (
          <div key={"hl-label-" + hi} style={{
            position: "absolute", left: proj.x, top: proj.y,
            transform: "translate(-50%, -50%)", opacity: labelOp,
            pointerEvents: "none", textAlign: "center", whiteSpace: "nowrap",
            textShadow: "0 2px 12px rgba(0,0,0,0.85), 0 0 30px rgba(0,0,0,0.5)",
          }}>
            <div style={{ fontFamily: "'Helvetica Neue', 'Inter', Arial, sans-serif",
              fontSize: size, fontWeight: weight, letterSpacing: spacing, color, lineHeight: 1 }}>
              {h.label.text}
            </div>
            {h.label.sub && (
              <div style={{ marginTop: 8, fontFamily: "'Helvetica Neue', 'Inter', Arial, sans-serif",
                fontSize: subSize, fontWeight: 300, letterSpacing: spacing * 0.5,
                color: subColor, opacity: 0.92 }}>
                {h.label.sub}
              </div>
            )}
          </div>
        );
      })}`;
}

function emitFlagBadges(): string {
  return `{HIGHLIGHTS.map((h, hi) => {
        const iso = (h.flag?.iso || h.countryISO || "").toLowerCase();
        if (!h.flag?.show || !iso) return null;
        const fade = h.fade ?? { in: CONFIG.hold / FRAMES, out: 1 };
        const fadeInF = Math.round(fade.in * FRAMES);
        const fadeOutF = Math.round(fade.out * FRAMES);
        const op = sInterp(frame, [fadeInF, fadeInF + 8, fadeOutF - 8, fadeOutF], [0, 1, 1, 0], { extrapolateLeft: "clamp", extrapolateRight: "clamp" });
        if (op < 0.01) return null;
        const proj = mapRef.current?.getMap()?.project(_centroid(h.geojson));
        if (!proj) return null;
        const w = h.flag.size ?? 220;
        const fh = Math.round(w * 0.66);
        const showCode = h.flag.showCode !== false;
        return (
          <div key={"hl-flag-" + hi} style={{
            position: "absolute", left: proj.x, top: proj.y,
            transform: "translate(-50%, -50%)", opacity: op, pointerEvents: "none",
            display: "flex", alignItems: "center", gap: Math.round(w * 0.09),
            padding: Math.round(w * 0.06) + "px " + Math.round(w * 0.1) + "px",
            borderRadius: Math.round(w * 0.07), background: "rgba(6,8,15,0.82)",
            border: "2px solid " + h.style.borderColor,
            boxShadow: "0 10px 40px rgba(0,0,0,0.55)", backdropFilter: "blur(6px)",
          }}>
            <img src={"https://flagcdn.com/w320/" + iso + ".png"} style={{
              width: w, height: fh, borderRadius: Math.round(w * 0.035), objectFit: "cover",
              boxShadow: "0 2px 10px rgba(0,0,0,0.5)" }} />
            {showCode && (
              <span style={{ fontFamily: "'Helvetica Neue', 'Inter', Arial, sans-serif",
                fontSize: Math.round(w * 0.26), fontWeight: 700, letterSpacing: Math.round(w * 0.02),
                color: "#ffffff", textShadow: "0 2px 10px rgba(0,0,0,0.8)" }}>
                {iso.toUpperCase()}
              </span>
            )}
          </div>
        );
      })}`;
}

function emitLabel(
  label: NonNullable<MapSceneSpec["labels"]>[number],
  i: number,
  palette: SceneSpec["style"]["palette"],
  lt: SceneSpec["style"]["labelTypography"],
  font: string,
  width: number,
  height: number,
  FRAMES: number,
): string {
  const opVar = `label${i}Op`;
  // Respect per-label fade in / out (fadeOut:false → hold to the end).
  const inA = label.primaryInFrame;
  const inB = inA + (label.fadeIn === false ? 0.001 : 6);
  const noOut = label.fadeOut === false;
  const outA = noOut ? FRAMES + 100 : label.primaryOutFrame;
  const outB = noOut ? FRAMES + 101 : label.primaryOutFrame + 8;
  const opExpr = `const ${opVar} = sInterp(frame, [${inA}, ${inB}, ${outA}, ${outB}], [0, 1, 1, 0], { extrapolateLeft: "clamp", extrapolateRight: "clamp" });`;

  // Per-label font override (#5) — falls back to the package font.
  const labelFontStack = JSON.stringify(
    `'${label.fontFamily ?? font}', 'Inter', Arial, sans-serif`,
  );

  // Per-label accent override — drives dot / ring / border / glow when set,
  // mirroring MapScene.tsx (`accent = label.accentColor ?? palette.borderColor`).
  // Falls back to the palette CONFIG refs so unset labels are unchanged.
  const accent = label.accentColor && /^#[0-9a-fA-F]{3,8}$/.test(label.accentColor) ? label.accentColor : null;
  const borderRef = accent ? JSON.stringify(accent) : "CONFIG.borderColor";
  const dotRef = accent ? JSON.stringify(accent) : "CONFIG.dotColor";
  const ringRef = accent ? JSON.stringify(accent) : "CONFIG.ringColor";

  if (label.layout === "city-projected" && label.projectLon != null) {
    return `{(() => {
        ${opExpr}
        const proj = mapRef.current?.getMap()?.project([${label.projectLon}, ${label.projectLat}]);
        const lx = proj ? proj.x : ${width / 2};
        const ly = proj ? proj.y : ${height / 2};
        if (${opVar} < 0.01) return null;
        return (
          <React.Fragment>
            <svg viewBox="0 0 ${width} ${height}" style={{ position: "absolute", inset: 0, width: "100%", height: "100%", pointerEvents: "none", opacity: ${opVar} }}>
              <circle cx={lx} cy={ly} r={56} fill="none" stroke={${ringRef}} strokeWidth={3} opacity={0.55} />
              <circle cx={lx} cy={ly} r={18} fill={${dotRef}} />
              <circle cx={lx} cy={ly} r={18} fill="none" stroke={${borderRef}} strokeWidth={3} />
            </svg>
            <div style={{
              position: "absolute",
              left: \`\${(lx / ${width}) * 100}%\`,
              top: \`\${(ly / ${height}) * 100}%\`,
              transform: "translate(-50%, -260%)",
              opacity: ${opVar}, pointerEvents: "none", textAlign: "center", whiteSpace: "nowrap"
            }}>
              <div style={{
                fontFamily: ${labelFontStack},
                fontSize: ${Math.round(lt.titleSize * 0.7)}, fontWeight: 200, letterSpacing: ${lt.titleSpacing},
                color: "#ffffff",
                textShadow: \`0 2px 24px rgba(0,0,0,0.9), 0 0 60px \${${borderRef}}4D\`,
              }}>${escapeJsx(label.primary)}</div>
              ${label.secondary ? `<div style={{
                marginTop: 10,
                fontFamily: ${labelFontStack},
                fontSize: ${Math.round(lt.subSize * 0.85)}, fontWeight: 300, letterSpacing: ${Math.round(lt.subSpacing * 0.7)},
                color: "rgba(255,255,255,0.7)",
                textShadow: "0 1px 10px rgba(0,0,0,0.85)",
              }}>${escapeJsx(label.secondary)}</div>` : ""}
            </div>
          </React.Fragment>
        );
      })()}`;
  }

  // bottom-banner
  return `{(() => {
        ${opExpr}
        const slideY = sInterp(frame, [${label.primaryInFrame}, ${label.primaryInFrame + 12}], [14, 0], { extrapolateLeft: "clamp", extrapolateRight: "clamp" });
        return (
          <div style={{
            position: "absolute", left: "50%", bottom: "12%",
            transform: \`translateX(-50%) translateY(\${slideY}px)\`,
            opacity: ${opVar}, pointerEvents: "none", textAlign: "center", whiteSpace: "nowrap",
          }}>
            <div style={{
              display: "inline-block", padding: "26px 72px",
              border: \`1.5px solid \${${borderRef}}aa\`,
              background: "rgba(6,8,15,0.55)", backdropFilter: "blur(4px)",
            }}>
              <div style={{
                fontFamily: ${labelFontStack},
                fontSize: ${lt.titleSize}, fontWeight: ${lt.titleWeight}, letterSpacing: ${lt.titleSpacing},
                color: "#ffffff",
                textShadow: \`0 2px 18px rgba(0,0,0,0.9), 0 0 50px \${${borderRef}}59\`,
              }}>${escapeJsx(label.primary)}</div>
              ${label.secondary ? `<div style={{
                marginTop: 14,
                fontFamily: ${labelFontStack},
                fontSize: ${lt.subSize}, fontWeight: 300, letterSpacing: ${lt.subSpacing},
                color: ${borderRef}, opacity: 0.92,
              }}>${escapeJsx(label.secondary)}</div>` : ""}
            </div>
          </div>
        );
      })()}`;
}

// `escapeStr` was promoted to escapeJsx in src/lib/codegen/util.ts
