import type { SceneSpec, QuoteSceneSpec } from "../types";
import { toComponentName, j } from "./util";

export function generateQuoteSceneTsx(spec: SceneSpec): string {
  const s = spec.scene as QuoteSceneSpec;
  const componentName = toComponentName(spec.name);
  const { palette, fonts, labelTypography, letterboxHeight } = spec.style;
  const serifFont = j(`'${fonts.primary.family}', 'Georgia', serif`);
  const sansFont = j(`'${fonts.primary.family}', 'Inter', Arial, sans-serif`);

  const fontScale = s.fontScale ?? 1;
  const accent = s.accentColor ?? palette.borderColor;
  const animation = s.animation ?? "fade-up";
  const quoteSize = Math.round(labelTypography.titleSize * 1.4 * fontScale);
  const attrSize = Math.round(labelTypography.subSize * 1.1 * fontScale);
  const halfWidth = Math.round(spec.width * (s.maxWidthPct ?? 0.8));
  const padX = Math.round(spec.width * 0.1);
  const leftPad = Math.round(spec.width * 0.1);
  const lift0 = animation === "fade-up" ? 30 : 0;
  const scale0 = animation === "scale" ? 0.92 : 1;

  const bg =
    s.background === "transparent"
      ? `"transparent"`
      : s.background === "gradient"
        ? `\`radial-gradient(ellipse at center, ${palette.fillColor}55 0%, #06080f 75%)\``
        : `"#06080f"`;

  const alignBlock = s.variant === "left"
    ? `{ textAlign: "left" as const, paddingLeft: ${leftPad}, alignItems: "flex-start" as const }`
    : `{ textAlign: "center" as const, alignItems: "center" as const }`;

  return `// AUTO-GENERATED by MAPANISY — edit in the studio, not here.
// Scene: ${spec.name}  ·  ${spec.durationSec}s @ ${spec.fps}fps  ·  ${spec.width}x${spec.height}

import React from "react";
import { AbsoluteFill, interpolate, useCurrentFrame } from "remotion";

const CONFIG = {
  quote: ${j(s.quote)},
  attribution: ${j(s.attribution)},
  context: ${j(s.context)},
  inFrame: ${s.reveal.inFrame},
  outFrame: ${s.reveal.outFrame},
  borderColor: ${j(accent)},
};

export const ${componentName}: React.FC = () => {
  const frame = useCurrentFrame();
  const op = interpolate(frame, [CONFIG.inFrame, CONFIG.inFrame + 12, CONFIG.outFrame - 18, CONFIG.outFrame],
    [0, 1, 1, 0], { extrapolateLeft: "clamp", extrapolateRight: "clamp" });
  const lift = interpolate(frame, [CONFIG.inFrame, CONFIG.inFrame + 24], [${lift0}, 0],
    { extrapolateLeft: "clamp", extrapolateRight: "clamp" });
  const scale = interpolate(frame, [CONFIG.inFrame, CONFIG.inFrame + 24], [${scale0}, 1],
    { extrapolateLeft: "clamp", extrapolateRight: "clamp" });

  return (
    <AbsoluteFill style={{ background: ${bg} }}>
      <AbsoluteFill style={{
        display: "flex", flexDirection: "column", justifyContent: "center",
        padding: \`0 ${padX}px\`,
        opacity: op, transform: \`translateY(\${lift}px) scale(\${scale})\`,
        ...${alignBlock},
      }}>
        <div style={{
          fontFamily: ${serifFont},
          fontSize: ${quoteSize}, fontWeight: 300, lineHeight: 1.15,
          color: "#ffffff", letterSpacing: -1, maxWidth: ${halfWidth},
          position: "relative",
        }}>
          ${s.showQuoteMarks ? `<span aria-hidden style={{
            position: "absolute",
            left: ${s.variant === "left" ? `-${Math.round(quoteSize * 0.7)}` : `"auto"`},
            top: -${Math.round(quoteSize * 0.45)},
            fontSize: ${Math.round(quoteSize * 1.8)},
            color: CONFIG.borderColor, opacity: 0.7, lineHeight: 1,
          }}>{"“"}</span>` : ""}
          {CONFIG.quote}
        </div>
        <div style={{
          marginTop: 60,
          fontFamily: ${sansFont},
          fontSize: ${attrSize}, fontWeight: 400,
          letterSpacing: ${labelTypography.subSpacing},
          color: CONFIG.borderColor,
        }}>— {CONFIG.attribution}</div>
        ${s.context ? `<div style={{
          marginTop: 10,
          fontFamily: ${sansFont},
          fontSize: ${Math.round(attrSize * 0.7)}, fontWeight: 300,
          letterSpacing: ${Math.round(labelTypography.subSpacing * 0.8)},
          color: "rgba(255,255,255,0.55)",
        }}>{CONFIG.context}</div>` : ""}
      </AbsoluteFill>

      ${s.background === "transparent" || letterboxHeight <= 0 ? "" : `<AbsoluteFill style={{ pointerEvents: "none" }}>
        <div style={{ position: "absolute", top: 0, left: 0, right: 0, height: ${letterboxHeight},
          background: "linear-gradient(to bottom, rgba(0,0,0,0.75), rgba(0,0,0,0))" }} />
        <div style={{ position: "absolute", bottom: 0, left: 0, right: 0, height: ${letterboxHeight},
          background: "linear-gradient(to top, rgba(0,0,0,0.75), rgba(0,0,0,0))" }} />
      </AbsoluteFill>`}
    </AbsoluteFill>
  );
};
`;
}
