import type { SceneSpec, TitleSceneSpec } from "../types";
import { toComponentName, j } from "./util";

export function generateTitleSceneTsx(spec: SceneSpec): string {
  const s = spec.scene as TitleSceneSpec;
  const componentName = toComponentName(spec.name);
  const { palette, fonts, labelTypography, letterboxHeight } = spec.style;

  // ── Resolve adjustable knobs (mirror src/remotion/TitleScene.tsx) ──────
  const template = s.template ?? "classic";
  const align = s.align ?? (s.variant === "left" ? "left" : "center");
  const position = s.position ?? "center";
  const titleScale = s.titleScale ?? 1;
  const accent = s.accentColor ?? palette.borderColor;
  const titleColor = s.titleColor ?? "#ffffff";
  const titleWeight = s.titleWeight ?? 200;
  const animation = s.animation ?? "fade-up";
  const maxWidthPct = s.maxWidthPct ?? 0.84;
  const serif = template === "serif";

  const fontExpr = j(
    serif ? `'Georgia', 'Times New Roman', serif` : `'${fonts.primary.family}', 'Inter', Arial, sans-serif`,
  );
  const titleText = s.uppercaseTitle ? (s.title ?? "").toUpperCase() : s.title;
  const titleSize = Math.round(labelTypography.titleSize * 1.8 * titleScale);

  const bgStyle =
    s.background === "transparent"
      ? `{ background: "transparent" }`
      : s.background === "gradient"
        ? `{ background: \`radial-gradient(ellipse at center, ${palette.fillColor}66 0%, #06080f 75%)\` }`
        : `{ background: "#06080f" }`;

  const justify = position === "top" ? "flex-start" : position === "bottom" ? "flex-end" : "center";
  const itemsAlign = align === "left" ? "flex-start" : align === "right" ? "flex-end" : "center";
  const sidePad = align === "center" ? 0 : Math.round(spec.width * 0.08);
  const vertPad = position === "center" ? 0 : Math.round(spec.height * 0.1);
  const useLeftBar = template === "stacked";
  const showUnderline = template === "impact" || s.variant === "split";
  const showSerifRule = template === "serif";

  // Kicker markup — pill for kicker-box, plain otherwise.
  const kickerMarkup = s.kicker
    ? template === "kicker-box"
      ? `<div style={{
          display: "inline-block", padding: "10px 22px", marginBottom: 28,
          background: ${j(accent)}, color: "#06080f", fontFamily: ${fontExpr},
          fontSize: ${Math.round(labelTypography.subSize)}, fontWeight: 700,
          letterSpacing: ${Math.round(labelTypography.subSpacing * 1.2)},
          textTransform: "uppercase", borderRadius: 4,
        }}>{${j(s.kicker)}}</div>`
      : `<div style={{
          fontFamily: ${fontExpr}, fontSize: ${Math.round(labelTypography.subSize * 1.2)}, fontWeight: 300,
          letterSpacing: ${Math.round(labelTypography.subSpacing * 1.6)}, color: ${j(accent)},
          marginBottom: ${template === "impact" ? 24 : 36},
          ${template === "impact" ? `textTransform: "uppercase",` : ``}
        }}>{${j(s.kicker)}}</div>`
    : "";

  const underlineMarkup = showUnderline
    ? `<div style={{
        marginTop: 36, alignSelf: ${j(itemsAlign)},
        width: ${template === "impact" ? 320 : 220}, height: ${template === "impact" ? 8 : 2},
        background: ${j(accent)}, borderRadius: 4,
        transform: \`scaleX(\${interpolate(frame, [CONFIG.inFrame + 6, CONFIG.inFrame + 22], [0, 1], { extrapolateLeft: "clamp", extrapolateRight: "clamp" })})\`,
        transformOrigin: ${align === "center" ? `"center"` : `"left"`},
      }} />`
    : showSerifRule
      ? `<div style={{ marginTop: 28, alignSelf: ${j(itemsAlign)}, width: 120, height: 1, background: ${j(accent)}, opacity: 0.8 }} />`
      : "";

  const subtitleMarkup = s.subtitle
    ? `<div style={{
        marginTop: ${template === "stacked" ? 14 : 40}, fontFamily: ${fontExpr},
        fontSize: ${Math.round(labelTypography.subSize * (template === "stacked" ? 1.0 : 1.4))}, fontWeight: 300,
        ${serif ? `fontStyle: "italic",` : ``}
        letterSpacing: ${labelTypography.subSpacing}, color: "rgba(255,255,255,0.72)",
      }}>{${j(s.subtitle)}}</div>`
    : "";

  // Animation transforms. word-reveal degrades to fade-up in the standalone file.
  const slideExpr =
    animation === "fade-up" || animation === "word-reveal"
      ? `interpolate(frame, [CONFIG.inFrame, CONFIG.inFrame + 14], [40, 0], { extrapolateLeft: "clamp", extrapolateRight: "clamp" })`
      : `0`;
  const scaleExpr =
    animation === "scale"
      ? `interpolate(frame, [CONFIG.inFrame, CONFIG.inFrame + 16], [0.9, 1], { extrapolateLeft: "clamp", extrapolateRight: "clamp" })`
      : `1`;
  const clipExpr =
    animation === "wipe"
      ? `\`inset(0 \${100 - interpolate(frame, [CONFIG.inFrame, CONFIG.inFrame + 18], [0, 100], { extrapolateLeft: "clamp", extrapolateRight: "clamp" })}% 0 0)\``
      : `undefined`;

  return `// AUTO-GENERATED by MAPANISY — edit in the studio, not here.
// Scene: ${spec.name}  ·  ${spec.durationSec}s @ ${spec.fps}fps  ·  ${spec.width}x${spec.height}
// Title template: ${template} (${animation})

import React from "react";
import { AbsoluteFill, interpolate, useCurrentFrame } from "remotion";

const CONFIG = {
  inFrame: ${s.reveal.inFrame},
  outFrame: ${s.reveal.outFrame},
  glowColor: ${j(palette.glowColor)},
};

export const ${componentName}: React.FC = () => {
  const frame = useCurrentFrame();
  const op = interpolate(frame, [CONFIG.inFrame, CONFIG.inFrame + 8, CONFIG.outFrame - 12, CONFIG.outFrame], [0, 1, 1, 0], { extrapolateLeft: "clamp", extrapolateRight: "clamp" });
  const slideY = ${slideExpr};
  const scale = ${scaleExpr};

  return (
    <AbsoluteFill style={${bgStyle}}>
      <AbsoluteFill style={{
        display: "flex", flexDirection: "column",
        justifyContent: ${j(justify)}, alignItems: ${j(itemsAlign)},
        textAlign: ${j(align)},
        paddingLeft: ${sidePad}, paddingRight: ${sidePad},
        paddingTop: ${position === "top" ? vertPad : 0}, paddingBottom: ${position === "bottom" ? vertPad : 0},
        transform: \`translateY(\${slideY}px) scale(\${scale})\`, opacity: op,
      }}>
        <div style={{
          display: "flex", flexDirection: "column", alignItems: ${j(itemsAlign)},
          maxWidth: ${Math.round(spec.width * maxWidthPct)},
          ${useLeftBar ? `paddingLeft: 40, borderLeft: \`8px solid ${accent}\`,` : ``}
        }}>
          ${kickerMarkup}
          <div style={{
            fontFamily: ${fontExpr}, fontSize: ${titleSize}, fontWeight: ${titleWeight},
            letterSpacing: ${Math.round(labelTypography.titleSpacing * (serif ? 0.2 : 0.6))},
            lineHeight: 1.05, color: ${j(titleColor)},
            textShadow: ${template === "impact" ? `"0 6px 40px rgba(0,0,0,0.5)"` : `\`0 0 80px \${CONFIG.glowColor}55\``},
            clipPath: ${clipExpr},
          }}>{${j(titleText)}}</div>
          ${underlineMarkup}
          ${subtitleMarkup}
        </div>
      </AbsoluteFill>

${s.background === "transparent" || letterboxHeight <= 0 ? `      {/* no letterbox */}` : `      <AbsoluteFill style={{ pointerEvents: "none" }}>
        <div style={{ position: "absolute", top: 0, left: 0, right: 0, height: ${letterboxHeight},
          background: "linear-gradient(to bottom, rgba(0,0,0,0.75), rgba(0,0,0,0))" }} />
        <div style={{ position: "absolute", bottom: 0, left: 0, right: 0, height: ${letterboxHeight},
          background: "linear-gradient(to top, rgba(0,0,0,0.75), rgba(0,0,0,0))" }} />
      </AbsoluteFill>`}
    </AbsoluteFill>
  );
};
`;
}
